### ISSUE TITLE
Update cost label

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/facilities.uiowa.edu#40]
Our director of Design & Construction wants us to display “Project Cost” instead of “Construction Cost” on our project pages. Can you change the labels for the project pages? I’m checking with Rakesh to see if we are sending the right field data.
Thanks.
 
Ex. Should say “Project Cost”

**Comment by richardbporter** [comment]
410397e120f0d1434516b2d974ee2c2bcdd4ff4a
