### ISSUE TITLE
Building coordinator updates

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/facilities.uiowa.edu#70]
https://facilities.stage.drupal.uiowa.edu/building-coordinators
 
```
1. Please change the text in the red box from “For maintenance emergencies…” to “For emergencies…” 

2.      Please add an editable region under the above two items where I can add the following information (these may change so I will need to be able to edit this area):
a.       “For all other requests, please use the FM@YourService portal”
“Building and Custodial Managers”
b.      Tom Moore, Manager, Building Operations & Maintenance (East and West Campus)
c.      Ann Rosenthal, Director, Facilities Operations (Oakdale Campus)
d.      Duane “Tiger” Lown, Manager, Custodial Services
e.      Jeff Rajtora,  Manager, Custodial Services
3.      In the table header row only if possible, please combine the last two columns “maintenance manager” and “custodial asst manager” into one and underneath add a link to the customer service portal: Please contact FM@YourService
```

I think the red text should be removed from the block and set by the customer. Item 2 can already be accomplished via the page building tools, the customer should do that. Item 3 might be difficult - I can assist with that.

**Comment by briand44** [comment]
@richardbporter Do you want me to add the emergency button back in the site using page building tools or do you plan on telling the customer how to do that?

**Comment by richardbporter** [comment]
You can add it back if you like.

**Comment by briand44** [comment]
@richardbporter So for 3 do they want us to combine all the data: areaManager, phone, email; CustodialSupervisor, phone, email and the link to the portal all in one column? Any chance they will expose that data in their API? I am not seeing it currently.
